-- 코드를 입력하세요
# 2022년 1월의 도서 판매 데이터 기준
# TOTAL_SALES = 판매량 * 판매가
SELECT
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(S.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK AS B, AUTHOR AS A, BOOK_SALES AS S
WHERE B.AUTHOR_ID = A.AUTHOR_ID
AND B.BOOK_ID = S.BOOK_ID
AND S.SALES_DATE LIKE '2022-01%'
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC