-- 코드를 입력하세요
WITH RECORD(MONTH, CAR_ID) AS (
    SELECT
        MONTH(START_DATE) AS MONTH,
        CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE DATE_FORMAT(START_DATE, "%Y-%m") BETWEEN "2022-08" AND "2022-10"
)
SELECT 
    R.MONTH,
    R.CAR_ID,
    COUNT(*) AS RECORDS
FROM RECORD R
WHERE (SELECT COUNT(*) FROM RECORD R2 WHERE R2.CAR_ID = R.CAR_ID) >= 5
GROUP BY R.MONTH, R.CAR_ID
ORDER BY R.MONTH ASC, R.CAR_ID DESC