-- 코드를 입력하세요
SELECT
    CONCAT(
        '/home/grep/src/', 
        F.BOARD_ID, '/',
        F.FILE_ID,
        F.FILE_NAME,
        F.FILE_EXT
    ) AS FILE_PATH
FROM USED_GOODS_FILE F, USED_GOODS_BOARD B
WHERE B.BOARD_ID = F.BOARD_ID
AND VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY FILE_ID DESC